/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.1
 * source: gravity/v1/ethereum_signer.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../gogoproto/gogo";
import * as pb_1 from "google-protobuf";
export namespace gravity.v1 {
    export enum SignType {
        SIGN_TYPE_UNSPECIFIED = 0,
        SIGN_TYPE_ORCHESTRATOR_SIGNED_MULTI_SIG_UPDATE = 1,
        SIGN_TYPE_ORCHESTRATOR_SIGNED_WITHDRAW_BATCH = 2
    }
}
